/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { PublicAPI } from "./public-api.js";

export class TracearrSDK extends ClientSDK {
  private _publicAPI?: PublicAPI;
  get publicAPI(): PublicAPI {
    return (this._publicAPI ??= new PublicAPI(this._options));
  }
}
