/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the tracearr-sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx publicAPIGetAPIV1PublicHealth.example.ts
 */

import { TracearrSDK } from "tracearr-sdk";

const tracearrSDK = new TracearrSDK({
  bearerAuth: process.env["TRACEARRSDK_BEARER_AUTH"] ?? "",
});

async function main() {
  const result = await tracearrSDK.publicAPI.getApiV1PublicHealth();

  console.log(result);
}

main().catch(console.error);
