/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Time range for activity data
 */
export const Period = {
  Week: "week",
  Month: "month",
  Year: "year",
} as const;
/**
 * Time range for activity data
 */
export type Period = ClosedEnum<typeof Period>;

export type GetApiV1PublicActivityRequest = {
  /**
   * Time range for activity data
   */
  period?: Period | undefined;
  /**
   * Filter by server
   */
  serverId?: string | undefined;
  /**
   * IANA timezone for date bucketing
   */
  timezone?: string | undefined;
};

/** @internal */
export const Period$outboundSchema: z.ZodMiniEnum<typeof Period> = z.enum(
  Period,
);

/** @internal */
export type GetApiV1PublicActivityRequest$Outbound = {
  period: string;
  serverId?: string | undefined;
  timezone: string;
};

/** @internal */
export const GetApiV1PublicActivityRequest$outboundSchema: z.ZodMiniType<
  GetApiV1PublicActivityRequest$Outbound,
  GetApiV1PublicActivityRequest
> = z.object({
  period: z._default(Period$outboundSchema, "month"),
  serverId: z.optional(z.string()),
  timezone: z._default(z.string(), "UTC"),
});

export function getApiV1PublicActivityRequestToJSON(
  getApiV1PublicActivityRequest: GetApiV1PublicActivityRequest,
): string {
  return JSON.stringify(
    GetApiV1PublicActivityRequest$outboundSchema.parse(
      getApiV1PublicActivityRequest,
    ),
  );
}
