/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetApiV1PublicStatsRequest = {
  /**
   * Filter by server
   */
  serverId?: string | undefined;
};

/** @internal */
export type GetApiV1PublicStatsRequest$Outbound = {
  serverId?: string | undefined;
};

/** @internal */
export const GetApiV1PublicStatsRequest$outboundSchema: z.ZodMiniType<
  GetApiV1PublicStatsRequest$Outbound,
  GetApiV1PublicStatsRequest
> = z.object({
  serverId: z.optional(z.string()),
});

export function getApiV1PublicStatsRequestToJSON(
  getApiV1PublicStatsRequest: GetApiV1PublicStatsRequest,
): string {
  return JSON.stringify(
    GetApiV1PublicStatsRequest$outboundSchema.parse(getApiV1PublicStatsRequest),
  );
}
