/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetApiV1PublicUsersRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  /**
   * Filter by server
   */
  serverId?: string | undefined;
};

/** @internal */
export type GetApiV1PublicUsersRequest$Outbound = {
  page: number;
  pageSize: number;
  serverId?: string | undefined;
};

/** @internal */
export const GetApiV1PublicUsersRequest$outboundSchema: z.ZodMiniType<
  GetApiV1PublicUsersRequest$Outbound,
  GetApiV1PublicUsersRequest
> = z.object({
  page: z._default(z.int(), 1),
  pageSize: z._default(z.int(), 25),
  serverId: z.optional(z.string()),
});

export function getApiV1PublicUsersRequestToJSON(
  getApiV1PublicUsersRequest: GetApiV1PublicUsersRequest,
): string {
  return JSON.stringify(
    GetApiV1PublicUsersRequest$outboundSchema.parse(getApiV1PublicUsersRequest),
  );
}
