/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetApiV1PublicStatsTodayRequest = {
  /**
   * Filter by server
   */
  serverId?: string | undefined;
  /**
   * IANA timezone for "today" calculation
   */
  timezone?: string | undefined;
};

/** @internal */
export type GetApiV1PublicStatsTodayRequest$Outbound = {
  serverId?: string | undefined;
  timezone: string;
};

/** @internal */
export const GetApiV1PublicStatsTodayRequest$outboundSchema: z.ZodMiniType<
  GetApiV1PublicStatsTodayRequest$Outbound,
  GetApiV1PublicStatsTodayRequest
> = z.object({
  serverId: z.optional(z.string()),
  timezone: z._default(z.string(), "UTC"),
});

export function getApiV1PublicStatsTodayRequestToJSON(
  getApiV1PublicStatsTodayRequest: GetApiV1PublicStatsTodayRequest,
): string {
  return JSON.stringify(
    GetApiV1PublicStatsTodayRequest$outboundSchema.parse(
      getApiV1PublicStatsTodayRequest,
    ),
  );
}
