/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetApiV1PublicStreamsRequest = {
  /**
   * Filter by server
   */
  serverId?: string | undefined;
  /**
   * Return only summary (omit data array)
   */
  summary?: boolean | null | undefined;
};

/**
 * Active streams retrieved
 */
export type GetApiV1PublicStreamsResponse =
  | models.StreamsResponse
  | models.StreamsSummaryOnlyResponse;

/** @internal */
export type GetApiV1PublicStreamsRequest$Outbound = {
  serverId?: string | undefined;
  summary?: boolean | null | undefined;
};

/** @internal */
export const GetApiV1PublicStreamsRequest$outboundSchema: z.ZodMiniType<
  GetApiV1PublicStreamsRequest$Outbound,
  GetApiV1PublicStreamsRequest
> = z.object({
  serverId: z.optional(z.string()),
  summary: z.optional(z.nullable(z.boolean())),
});

export function getApiV1PublicStreamsRequestToJSON(
  getApiV1PublicStreamsRequest: GetApiV1PublicStreamsRequest,
): string {
  return JSON.stringify(
    GetApiV1PublicStreamsRequest$outboundSchema.parse(
      getApiV1PublicStreamsRequest,
    ),
  );
}

/** @internal */
export const GetApiV1PublicStreamsResponse$inboundSchema: z.ZodMiniType<
  GetApiV1PublicStreamsResponse,
  unknown
> = smartUnion([
  models.StreamsResponse$inboundSchema,
  models.StreamsSummaryOnlyResponse$inboundSchema,
]);

export function getApiV1PublicStreamsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1PublicStreamsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiV1PublicStreamsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1PublicStreamsResponse' from JSON`,
  );
}
