/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type PostApiV1PublicStreamsIdTerminateRequest = {
  /**
   * Session ID from /streams
   */
  id: string;
  body?: models.TerminateStreamBody | undefined;
};

/** @internal */
export type PostApiV1PublicStreamsIdTerminateRequest$Outbound = {
  id: string;
  body?: models.TerminateStreamBody$Outbound | undefined;
};

/** @internal */
export const PostApiV1PublicStreamsIdTerminateRequest$outboundSchema:
  z.ZodMiniType<
    PostApiV1PublicStreamsIdTerminateRequest$Outbound,
    PostApiV1PublicStreamsIdTerminateRequest
  > = z.object({
    id: z.string(),
    body: z.optional(models.TerminateStreamBody$outboundSchema),
  });

export function postApiV1PublicStreamsIdTerminateRequestToJSON(
  postApiV1PublicStreamsIdTerminateRequest:
    PostApiV1PublicStreamsIdTerminateRequest,
): string {
  return JSON.stringify(
    PostApiV1PublicStreamsIdTerminateRequest$outboundSchema.parse(
      postApiV1PublicStreamsIdTerminateRequest,
    ),
  );
}
