/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { ServerStatus, ServerStatus$inboundSchema } from "./server-status.js";

export const Status = {
  Ok: "ok",
} as const;
export type Status = ClosedEnum<typeof Status>;

export type HealthResponse = {
  status: Status;
  /**
   * Tracearr server version
   */
  version: string;
  timestamp: Date;
  servers: Array<ServerStatus>;
};

/** @internal */
export const Status$inboundSchema: z.ZodMiniEnum<typeof Status> = z.enum(
  Status,
);

/** @internal */
export const HealthResponse$inboundSchema: z.ZodMiniType<
  HealthResponse,
  unknown
> = z.object({
  status: Status$inboundSchema,
  version: types.string(),
  timestamp: types.date(),
  servers: z.array(ServerStatus$inboundSchema),
});

export function healthResponseFromJSON(
  jsonString: string,
): SafeParseResult<HealthResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HealthResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HealthResponse' from JSON`,
  );
}
