/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";
import {
  SessionHistory,
  SessionHistory$inboundSchema,
} from "./session-history.js";

export type HistoryResponse = {
  data: Array<SessionHistory>;
  meta: PaginationMeta;
};

/** @internal */
export const HistoryResponse$inboundSchema: z.ZodMiniType<
  HistoryResponse,
  unknown
> = z.object({
  data: z.array(SessionHistory$inboundSchema),
  meta: PaginationMeta$inboundSchema,
});

export function historyResponseFromJSON(
  jsonString: string,
): SafeParseResult<HistoryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HistoryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HistoryResponse' from JSON`,
  );
}
