/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type PaginationMeta = {
  total: number;
  page: number;
  pageSize: number;
};

/** @internal */
export const PaginationMeta$inboundSchema: z.ZodMiniType<
  PaginationMeta,
  unknown
> = z.object({
  total: types.number(),
  page: types.number(),
  pageSize: types.number(),
});

export function paginationMetaFromJSON(
  jsonString: string,
): SafeParseResult<PaginationMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaginationMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginationMeta' from JSON`,
  );
}
