/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type QualityBreakdown = {
  directPlay: number;
  directStream: number;
  transcode: number;
  total: number;
  /**
   * Rounded percentage
   */
  directPlayPercent: number;
  directStreamPercent: number;
  transcodePercent: number;
};

/** @internal */
export const QualityBreakdown$inboundSchema: z.ZodMiniType<
  QualityBreakdown,
  unknown
> = z.object({
  directPlay: types.number(),
  directStream: types.number(),
  transcode: types.number(),
  total: types.number(),
  directPlayPercent: types.number(),
  directStreamPercent: types.number(),
  transcodePercent: types.number(),
});

export function qualityBreakdownFromJSON(
  jsonString: string,
): SafeParseResult<QualityBreakdown, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QualityBreakdown$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QualityBreakdown' from JSON`,
  );
}
