/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type SourceAudioDetails = {
  bitrate?: number | undefined;
  channelLayout?: string | undefined;
  language?: string | undefined;
  sampleRate?: number | undefined;
};

/** @internal */
export const SourceAudioDetails$inboundSchema: z.ZodMiniType<
  SourceAudioDetails,
  unknown
> = z.object({
  bitrate: types.optional(types.number()),
  channelLayout: types.optional(types.string()),
  language: types.optional(types.string()),
  sampleRate: types.optional(types.number()),
});

export function sourceAudioDetailsFromJSON(
  jsonString: string,
): SafeParseResult<SourceAudioDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SourceAudioDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SourceAudioDetails' from JSON`,
  );
}
