/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type SourceVideoDetails = {
  bitrate?: number | undefined;
  framerate?: string | undefined;
  dynamicRange?: string | undefined;
  aspectRatio?: number | undefined;
  profile?: string | undefined;
  level?: string | undefined;
  colorSpace?: string | undefined;
  colorDepth?: number | undefined;
};

/** @internal */
export const SourceVideoDetails$inboundSchema: z.ZodMiniType<
  SourceVideoDetails,
  unknown
> = z.object({
  bitrate: types.optional(types.number()),
  framerate: types.optional(types.string()),
  dynamicRange: types.optional(types.string()),
  aspectRatio: types.optional(types.number()),
  profile: types.optional(types.string()),
  level: types.optional(types.string()),
  colorSpace: types.optional(types.string()),
  colorDepth: types.optional(types.number()),
});

export function sourceVideoDetailsFromJSON(
  jsonString: string,
): SafeParseResult<SourceVideoDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SourceVideoDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SourceVideoDetails' from JSON`,
  );
}
