/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type StatsResponse = {
  activeStreams: number;
  totalUsers: number;
  /**
   * Sessions in last 30 days
   */
  totalSessions: number;
  /**
   * Violations in last 7 days
   */
  recentViolations: number;
  timestamp: Date;
};

/** @internal */
export const StatsResponse$inboundSchema: z.ZodMiniType<
  StatsResponse,
  unknown
> = z.object({
  activeStreams: types.number(),
  totalUsers: types.number(),
  totalSessions: types.number(),
  recentViolations: types.number(),
  timestamp: types.date(),
});

export function statsResponseFromJSON(
  jsonString: string,
): SafeParseResult<StatsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StatsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StatsResponse' from JSON`,
  );
}
