/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  StreamsSummary,
  StreamsSummary$inboundSchema,
} from "./streams-summary.js";

export type StreamsSummaryOnlyResponse = {
  summary: StreamsSummary;
};

/** @internal */
export const StreamsSummaryOnlyResponse$inboundSchema: z.ZodMiniType<
  StreamsSummaryOnlyResponse,
  unknown
> = z.object({
  summary: StreamsSummary$inboundSchema,
});

export function streamsSummaryOnlyResponseFromJSON(
  jsonString: string,
): SafeParseResult<StreamsSummaryOnlyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StreamsSummaryOnlyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamsSummaryOnlyResponse' from JSON`,
  );
}
