/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { Stream, Stream$inboundSchema } from "./stream.js";
import {
  StreamsSummary,
  StreamsSummary$inboundSchema,
} from "./streams-summary.js";

export type StreamsResponse = {
  data: Array<Stream>;
  summary: StreamsSummary;
};

/** @internal */
export const StreamsResponse$inboundSchema: z.ZodMiniType<
  StreamsResponse,
  unknown
> = z.object({
  data: z.array(Stream$inboundSchema),
  summary: StreamsSummary$inboundSchema,
});

export function streamsResponseFromJSON(
  jsonString: string,
): SafeParseResult<StreamsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StreamsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamsResponse' from JSON`,
  );
}
