/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type StreamAudioDetails = {
  bitrate?: number | undefined;
  channels?: number | undefined;
  language?: string | undefined;
};

/** @internal */
export const StreamAudioDetails$inboundSchema: z.ZodMiniType<
  StreamAudioDetails,
  unknown
> = z.object({
  bitrate: types.optional(types.number()),
  channels: types.optional(types.number()),
  language: types.optional(types.string()),
});

export function streamAudioDetailsFromJSON(
  jsonString: string,
): SafeParseResult<StreamAudioDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StreamAudioDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamAudioDetails' from JSON`,
  );
}
