/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ServerStreamSummary,
  ServerStreamSummary$inboundSchema,
} from "./server-stream-summary.js";

export type StreamsSummary = {
  total: number;
  transcodes: number;
  directStreams: number;
  directPlays: number;
  totalBitrate: string;
  byServer: Array<ServerStreamSummary>;
};

/** @internal */
export const StreamsSummary$inboundSchema: z.ZodMiniType<
  StreamsSummary,
  unknown
> = z.object({
  total: types.number(),
  transcodes: types.number(),
  directStreams: types.number(),
  directPlays: types.number(),
  totalBitrate: types.string(),
  byServer: z.array(ServerStreamSummary$inboundSchema),
});

export function streamsSummaryFromJSON(
  jsonString: string,
): SafeParseResult<StreamsSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StreamsSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamsSummary' from JSON`,
  );
}
