/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type StreamVideoDetails = {
  bitrate?: number | undefined;
  width?: number | undefined;
  height?: number | undefined;
  framerate?: string | undefined;
  dynamicRange?: string | undefined;
};

/** @internal */
export const StreamVideoDetails$inboundSchema: z.ZodMiniType<
  StreamVideoDetails,
  unknown
> = z.object({
  bitrate: types.optional(types.number()),
  width: types.optional(types.number()),
  height: types.optional(types.number()),
  framerate: types.optional(types.string()),
  dynamicRange: types.optional(types.string()),
});

export function streamVideoDetailsFromJSON(
  jsonString: string,
): SafeParseResult<StreamVideoDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StreamVideoDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamVideoDetails' from JSON`,
  );
}
