/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type SubtitleInfo = {
  decision?: string | undefined;
  codec?: string | undefined;
  language?: string | undefined;
  forced?: boolean | undefined;
};

/** @internal */
export const SubtitleInfo$inboundSchema: z.ZodMiniType<SubtitleInfo, unknown> =
  z.object({
    decision: types.optional(types.string()),
    codec: types.optional(types.string()),
    language: types.optional(types.string()),
    forced: types.optional(types.boolean()),
  });

export function subtitleInfoFromJSON(
  jsonString: string,
): SafeParseResult<SubtitleInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubtitleInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubtitleInfo' from JSON`,
  );
}
