/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TerminateStreamResponse = {
  success: true;
  terminationLogId: string;
  message: string;
};

/** @internal */
export const TerminateStreamResponse$inboundSchema: z.ZodMiniType<
  TerminateStreamResponse,
  unknown
> = z.object({
  success: types.literal(true),
  terminationLogId: types.string(),
  message: types.string(),
});

export function terminateStreamResponseFromJSON(
  jsonString: string,
): SafeParseResult<TerminateStreamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TerminateStreamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TerminateStreamResponse' from JSON`,
  );
}
