/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TerminateStreamBody = {
  /**
   * Message to display to user before termination
   */
  reason?: string | undefined;
};

/** @internal */
export type TerminateStreamBody$Outbound = {
  reason?: string | undefined;
};

/** @internal */
export const TerminateStreamBody$outboundSchema: z.ZodMiniType<
  TerminateStreamBody$Outbound,
  TerminateStreamBody
> = z.object({
  reason: z.optional(z.string()),
});

export function terminateStreamBodyToJSON(
  terminateStreamBody: TerminateStreamBody,
): string {
  return JSON.stringify(
    TerminateStreamBody$outboundSchema.parse(terminateStreamBody),
  );
}
