/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";
import { User, User$inboundSchema } from "./user.js";

export type UsersResponse = {
  data: Array<User>;
  meta: PaginationMeta;
};

/** @internal */
export const UsersResponse$inboundSchema: z.ZodMiniType<
  UsersResponse,
  unknown
> = z.object({
  data: z.array(User$inboundSchema),
  meta: PaginationMeta$inboundSchema,
});

export function usersResponseFromJSON(
  jsonString: string,
): SafeParseResult<UsersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsersResponse' from JSON`,
  );
}
