/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";
import { Violation, Violation$inboundSchema } from "./violation.js";

export type ViolationsResponse = {
  data: Array<Violation>;
  meta: PaginationMeta;
};

/** @internal */
export const ViolationsResponse$inboundSchema: z.ZodMiniType<
  ViolationsResponse,
  unknown
> = z.object({
  data: z.array(Violation$inboundSchema),
  meta: PaginationMeta$inboundSchema,
});

export function violationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ViolationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ViolationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ViolationsResponse' from JSON`,
  );
}
